### DISCUSSION TITLE
第二个博客搭建之Docusaurus - 愧怍的小站

### DISCUSSION THREAD

**Discussion by giscus** [kuizuo/blog#180] [General]
# 第二个博客搭建之Docusaurus - 愧怍的小站

博客地址: 愧怍的小站

https://kuizuo.cn/second-blog-is-docusaurus

**Comment by disnox** [comment]
感谢大佬的分享

**Reply by kuizuo** [reply]
😀

**Reply by disnox** [reply]
哈哈，我也照着大佬的框架搭了一个，不过我不是学前端的，我学的嵌入式，所以很多地方都不怎么会改，就直接照着模板来用了，大佬的主题风格我挺喜欢的，是我喜欢的口味，没其他意思，就是小弟可不可以直接用这个模板😍

**Reply by kuizuo** [reply]
MIT开源，自然可以随便用，如果帮到你的话不妨给个star🥳

**Reply by disnox** [reply]
好的好的，谢谢大佬

**Comment by BlueLanM** [comment]
😲大佬太厉害了，看了你的一些博客才知道原来真的有人这么有毅力，向你学习

**Reply by kuizuo** [reply]
说来惭愧，寒假这些天处于半摆烂的状态，主要生物钟乱了好几波，学习状态都差的要死。

**Reply by BlueLanM** [reply]
大佬请教一下，关于你博客中的自定义组件，我看官方文档中写的需要在src/pages下创建文件才会生成路由，我看了下你的源码，请问下你的tags标签页是怎么做到的呢

**Reply by BlueLanM** [reply]
因为我在源码里没看到pages文件夹下有tags😂

**Reply by kuizuo** [reply]
首先，tags 标签页是由 docusaurus 自动生成的，会根据 md 文档中的 yaml 配置，例如本文的 yaml 配置

```yaml
---
slug: second-blog-is-docusaurus
title: 第二个博客搭建之Docusaurus
date: 2021-08-20
authors: kuizuo
tags: [blog, docusaurus, project]
keywords: [blog, docusaurus, project]
---

正文部分...
```

这时 docusaurus 就会生成 /tags 路由(页面)，为官方的[theme/BlogTagsListPage](https://docusaurus.io/zh-CN/docs/next/api/plugins/@docusaurus/plugin-content-blog#blogTagsListComponent)。事实上有很多路由都是自动生成的，并且有相应的组件。

如果你想像我一样修改官方的 BlogTagsListPage 组件(页面)，你可以通过[swizz](https://docusaurus.io/zh-CN/docs/next/swizzling)的方式，然后在项目工程中 [src/theme/BlogTagsListPage](https://github.com/kuizuo/blog/blob/main/src/theme/BlogTagsListPage/index.tsx) 修改你想要的样式或是功能。
