### DISCUSSION TITLE
关于图片默认居中

### DISCUSSION THREAD

**Discussion by kcxain** [kuizuo/blog#211] [General]
您好，我想问下您的博客主题是如何设置 markdown 中的图片默认居中的呢？

**Comment by kuizuo** [comment]
其实就几行 [css 代码](https://github.com/kuizuo/blog/blob/adbd9671d9b3ea45020cddf257268ac6b9393dff/src/css/custom.scss#L229-L232)，你通过 F12 打开开发者面板便可查看到

``` css
.markdown img {
    display: flex;
    margin: 0 auto;
}
```
注释掉 `margin: 0 auto;` 便不会居中，如图所示

![image](https://github.com/kuizuo/blog/assets/61005888/d71c1e8d-602c-4ee0-8690-c92d3a3b6629)
